// <auto-generated />
namespace Personal_Shopping_Cart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changed_product_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_product_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201503281032263_changed_product_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
