// <auto-generated />
namespace Shopping_Cart_Personal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class product_table_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_table_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201503281103216_product_table_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
